{% set name = "flake8-print" %}
{% set version = "3.1.3" %}
{% set sha256 = "41b042646b72f1f8f8ce0eda5a8e48a640113a6c794c9348f4101fd08472af8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - flake8 >=2.1
    - pycodestyle
    - six

test:
  commands:
    - "flake8 --version | grep flake8-print:"

about:
  home: https://github.com/jbkahn/flake8-print
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flake8 plugin to check for print statements in python files.'
  dev_url: https://github.com/jbkahn/flake8-print

extra:
  recipe-maintainers:
    - dopplershift
